version: "3"

services:
#
# market server Conf
#
  local-market-server:
    image: ramesesinc/local-market-server:v001
    container_name: local-market-server
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ./env.conf
      - ../_custom/env.conf
    ports:
      - "8074:8070"
